### ISSUE TITLE
Discrepancy between this library and the published guidelines on Paragon

### ISSUE THREAD

**Issue by i-hardy** [bbc/gel-typography#55]
The guidelines here http://www.bbc.co.uk/gel/guidelines/typography#type-sizes indicate that Paragon in group C will be 28/32- however in `lib/_settings.scss` it's set at 30/34.

I'm guessing that the latter is correct, based on the pattern with other sizes, but just wanted to flag this up. Thanks for open-sourcing this library, it's been extremely helpful!

**Comment by tom-wr** [comment]
Good spot! Actually the guidelines are correct and the code is wrong. Both group C and D should be 28/32. Thanks - I'll look at making the changes.

**Comment by i-hardy** [comment]
Thanks! I'm happy to put in a PR if that would help.

**Comment by tom-wr** [comment]
That would be great - cheers.

**Comment by randombitsUK** [comment]
Issue addressed in https://github.com/bbc/gel-typography/pull/58
